export const apiRouter = {
    TOP_GAINERS:'TOP_GAINERS_LOSERS',
    OVERVIEW:'OVERVIEW',
    DAILY:'TIME_SERIES_DAILY',
    MONTHLY:'TIME_SERIES_MONTHLY',
    WEEKLY:'TIME_SERIES_WEEKLY',
    SEARCH:'SYMBOL_SEARCH'
    }
 